before:
  hooks:
    - make init
    - make remod
    - make test
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - x86_64
    goos:
      - linux
      - darwin
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
