before:
  hooks:
    - make test
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - darwin
archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  use: github-native
